# Generated by Django 2.2.6 on 2019-10-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191021_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.FileField(default='profile/team.jpg', upload_to='profile/'),
        ),
    ]
