# Generated by Django 2.2.6 on 2019-10-22 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='song_id',
            new_name='song',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='user_id',
            new_name='user',
        ),
    ]
